---
- hosts: all
  become: true

  vars:
    realtime_version: 0.7.4
    realtime_checksum: sha1:9971212a8d39ada4385b97b44486e30230223116

  tasks:
    - include_tasks: tasks/setup-system.yml

    - include_tasks: tasks/setup-realtime.yml

    - name: Remove temp dir at $HOME
      shell: rm -rf ~/.ansible
